# Generated by Django 4.2.4 on 2023-12-20 18:03

from django.db import migrations


def create_types_of_question(apps, schema_editor):
    list_of_question_types = [
        'open',
        'close_one',
        'close_many',
    ]

    TypeOfQuestion = apps.get_model("quiz", "TypeOfQuestion")

    for name in list_of_question_types:
        TypeOfQuestion.objects.create(question_type_name=name)
        print(name, ' CREATED')


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_types_of_question)
    ]
