# Generated by Django 4.2.4 on 2024-02-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_count',
            field=models.IntegerField(default=0, verbose_name='Number of questions'),
        ),
    ]
